# Site Settings
title: Hear My Roar
email: GeneralSandman@163.com
description: 追求卓越
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.dissigil.cn" # the base hostname & protocol for your site
google_analytics: ""

# User Settings
username: GeneralSandman
user_description: 爱编程，爱运动，C++服务器，努力中！
disqus_username: GeneralSandman

# Social Media
# Remove the item if you don't need it
github_username: GeneralSandman
# facebook_username: facebook_username
# twitter_username: twitter_username
# instagram_username: instagram_username
# linkedin_username: linkedin_username
# medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
